---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: "latest"

inputs:
- name: attendee-service-source

run:
  path: attendee-service-source/ci/tasks/smoke-test.sh

params:
  ATTENDEE_SERVICE_URL:
